### ISSUE TITLE
Field allow_method not included in Signature

### ISSUE THREAD

**Issue by eapmartins** [clicksign/clicksign-java#5]
this field "allow_method" is described in the documentation: https://clicksign.readme.io/docs/lista-de-assinatura but it is not in the class Signature, also in ClicksignResource.

**Comment by mbbernstein** [comment]
@eapmartins Essa biblioteca está desatualizada. Por favor, veja as correções sugeridas nesses PRs: https://github.com/clicksign/clicksign-java/pulls.
